services:
  
  api: 
    build:
      context: ./api
      dockerfile: .
    container_name: alertstream_api
    restart: unless-stopped
    volumes: 
      - ./api/_data:/app/_data
    ports: 
    - 8080:8080

  app: 
    build:
      context: ./app
      dockerfile: .
    container_name: alertstream_app
    restart: unless-stopped
    ports: 
    - 8081:8081