services:
  
  alertstream: 
    build:
      context: ./app
      dockerfile: .
    container_name: alertstream 
    restart: unless-stopped
    volumes: 
      - ./alertstream/data:/app/data
    ports: 
    - 8080:8080
  
  redis: 
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server /var/redis/conf/redis.conf
    volumes:
      - ./redis/conf:/var/redis/conf
      - ./redis/data:/data
    ports: 
      - 6379:6379