FROM denoland/deno:2.0.2
# see https://github.com/denoland/deno_docker/blob/main/example/Dockerfile

# The port that your application listens to.
EXPOSE 8080
WORKDIR /app

# These steps will be re-run upon each file change in your working directory:
COPY . .

# Compile the main app so that it doesn't need to be compiled each startup/entry.
RUN deno install
RUN deno cache main.tsx

CMD ["deno", "run", "-A", "main.tsx"]